name: CI tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: ["21.1", '20.3']
    container:
      image: erlang:${{matrix.erlang}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        env:
          cache-name: rebar3
        with:
          path: |
           ~/.cache/rebar3
           _build
          key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}
          restore-keys: |
            ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3
            ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}
      - name: tests
        run: make test
