name: Test CI
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: ['24']
    container:
      image: erlang:${{matrix.erlang}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        env:
          cache-name: rebar3
        with:
          path: |
           ~/.cache/rebar3
           _build
          key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}
          restore-keys: |
            ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3
            ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}
      - name: elvis
        run: make elvis
      - name: xref
        run: make xref
      - name: eunit
        run: make eunit
      - name: dialyzer
        run: make dialyzer
